#!/usr/bin/env node
/**
 * MPL State Management Utility
 * Shared helpers for reading/writing .mpl/state.json
 * Based on design document section 12.2
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, renameSync, rmSync } from 'fs';
import { join } from 'path';
import { randomBytes } from 'crypto';
import { loadConfig } from './mpl-config.mjs';

const STATE_DIR = '.mpl';
const STATE_FILE = 'state.json';

/**
 * Default state schema (design doc section 12.2)
 */
const DEFAULT_STATE = {
  pipeline_id: null,
  run_mode: 'full',
  tool_mode: 'full',         // F-04: "full" | "partial" | "standalone"
  pp_proximity: null,        // Hat model: "near" | "mid" | "far" (set by Triage)
  pp_score: null,            // Hat model: float 0.0~1.0 (set by Quick Scope Scan)
  worktree_history: [],      // History of worktree switches
  interview_depth: null,     // "skip" | "light" | "full" (set by Triage Step 0.2)
  current_phase: 'phase1-plan',
  started_at: null,
  finalize_done: false,      // Set to true when Step 5 finalization completes
  sprint_status: {
    total_todos: 0,
    completed_todos: 0,
    in_progress_todos: 0,
    failed_todos: 0
  },
  gate_results: {
    hard1_passed: null,
    hard2_passed: null,
    hard3_passed: null,
    advisory_passed: null
  },
  fix_loop_count: 0,
  max_fix_loops: 10,
  compaction_count: 0,
  last_phase_compaction_count: 0,
  session_id: null,
  cost: {
    total_tokens: 0,
    estimated_usd: 0
  },
  convergence: {
    pass_rate_history: [],
    stagnation_window: 3,
    min_improvement: 0.05,
    regression_threshold: -0.10
  },
  research: {
    status: null,           // null | 'stage1' | 'stage2' | 'stage3' | 'completed' | 'skipped'
    started_at: null,
    completed_at: null,
    stages_completed: [],   // ['stage1', 'stage2', 'stage3']
    report_path: null,      // '.mpl/research/report.md' or '.mpl/research/brief.md'
    findings_count: 0,
    sources_count: 0,
    mode: 'full',           // 'full' (3-stage) | 'light' (stage 1 only) | 'standalone'
    error: null,            // failure error message
    degraded_stages: []     // stages with partial failures, e.g. ['stage2']
  },
  memory: {                  // F-25: 4-Tier Adaptive Memory statistics
    episodic_entries: 0,
    semantic_rules: 0,
    procedural_entries: 0,
    last_compression: null,       // ISO timestamp of last episodic compression
    last_semantic_promotion: null  // ISO timestamp of last semantic promotion
  },
  h_item_metrics: {            // LT-05: H-Item severity feedback loop (v0.8.6)
    h_item_total: 0,            // Total H-items generated by verification planner
    h_item_side_interviews: 0,  // HIGH H-items that triggered side interviews
    h_item_review_rate: 0.0,    // Fraction of H-items reviewed by user in Step 5.1.8
    severity_overrides: {       // User reclassifications in Step 5.1.8
      high_to_med: 0,           // Planner said HIGH, user downgraded to MED
      high_to_low: 0,           // Planner said HIGH, user downgraded to LOW
      med_to_high: 0,           // Planner said MED, user upgraded to HIGH
      low_to_high: 0            // Planner said LOW, user upgraded to HIGH
    }
  },
  // Stage 2 ambiguity score — written by orchestrator via mpl_state_write after
  // the inline mpl_score_ambiguity MCP tool loop reaches threshold_met == true.
  // mpl-phase-controller blocks mpl-decompose if null.
  ambiguity_score: null,         // number (0.0~1.0) | null — threshold: <= 0.2
  // F-33: Session budget prediction
  session_status: null,          // null | "active" | "paused_budget"
  pause_reason: null,            // human-readable pause reason
  resume_from_phase: null,       // phase ID to resume from
  pause_timestamp: null,         // ISO timestamp of pause
  budget_at_pause: null,         // { context_pct, estimated_needed_pct }
};

// Prototype pollution guard keys
const DANGEROUS_KEYS = new Set(['__proto__', 'constructor', 'prototype']);

/**
 * Read MPL state from .mpl/state.json
 * @param {string} cwd - Working directory
 * @returns {object|null} State object or null if not found/invalid
 */
export function readState(cwd) {
  try {
    const statePath = join(cwd, STATE_DIR, STATE_FILE);
    if (!existsSync(statePath)) return null;
    const parsed = JSON.parse(readFileSync(statePath, 'utf-8'));
    // M5: Minimal schema validation
    if (typeof parsed !== 'object' || parsed === null) return null;
    if (!parsed.current_phase) return null;
    return parsed;
  } catch {
    return null;
  }
}

/**
 * Write/merge MPL state to .mpl/state.json (atomic via temp + rename)
 * @param {string} cwd - Working directory
 * @param {object} patch - Fields to merge into state
 * @returns {object} Merged state
 */
export function writeState(cwd, patch) {
  const stateDir = join(cwd, STATE_DIR);
  if (!existsSync(stateDir)) {
    mkdirSync(stateDir, { recursive: true });
  }

  const current = readState(cwd) || { ...DEFAULT_STATE };
  const merged = deepMerge(current, patch);

  // C2: Atomic write via temp file + rename
  const tmpPath = join(stateDir, `.state-${randomBytes(4).toString('hex')}.tmp`);
  writeFileSync(tmpPath, JSON.stringify(merged, null, 2), { mode: 0o600 });
  renameSync(tmpPath, join(stateDir, STATE_FILE));

  return merged;
}

/**
 * Check if MPL is currently active
 * @param {string} cwd - Working directory
 * @returns {boolean}
 */
export function isMplActive(cwd) {
  // M6: Check file existence separately from readState
  const statePath = join(cwd, STATE_DIR, STATE_FILE);
  if (!existsSync(statePath)) return false; // No file = truly inactive

  const state = readState(cwd);
  if (!state) return true; // File exists but corrupt/invalid = fail-closed (assume active)
  if (!state.current_phase) return false;
  // Active if phase is not null and not finalized
  return state.current_phase !== 'completed' && state.current_phase !== 'cancelled';
}

/**
 * Initialize MPL state for a new pipeline run
 * @param {string} cwd - Working directory
 * @param {string} featureName - Name of the feature being built
 * @param {string} runMode - Pipeline mode: 'full' (5-phase) or 'small' (3-phase lightweight)
 * @returns {object} Initial state
 */
/**
 * Pipeline-scoped paths that must be RESET on new pipeline start.
 * These are relative to cwd.
 */
const PIPELINE_SCOPE_PATHS = [
  // Root-level pipeline artifacts
  '.mpl/state.json',
  '.mpl/PLAN.md',
  '.mpl/auto-permit-learned.json',
  // Signals (transient)
  '.mpl/signals',
  // MPL pipeline artifacts (entire subtree except profile)
  '.mpl/mpl/state.json',
  '.mpl/mpl/decomposition.yaml',
  '.mpl/mpl/phase-decisions.md',
  '.mpl/mpl/codebase-analysis.json',
  '.mpl/mpl/RUNBOOK.md',
  '.mpl/mpl/phase0',
  '.mpl/mpl/phases',
  '.mpl/mpl/checkpoints',
  // Research artifacts
  '.mpl/research',
  // Working memory (ephemeral per pipeline)
  '.mpl/memory/working.md',
  // Context usage (transient)
  '.mpl/context-usage.json',
];

/**
 * Project-scoped paths that must NEVER be deleted.
 * Listed here for documentation; cleanPipelineScope only touches PIPELINE_SCOPE_PATHS.
 *
 * PERSIST:
 *   .mpl/config.json              - user settings
 *   .mpl/pivot-points.md          - reusable interview constraints
 *   .mpl/discoveries.md           - master discovery log
 *   .mpl/memory/semantic.md       - generalized patterns (3+ repetitions)
 *   .mpl/memory/procedural.jsonl  - tool usage patterns
 *   .mpl/memory/episodic.md       - phase history (time-compressed)
 *   .mpl/memory/learnings.md      - distilled project knowledge
 *   .mpl/memory/routing-patterns.jsonl - tier prediction history
 *   .mpl/cache/                   - phase0 cache (7-day TTL, self-expiring)
 *   .mpl/mpl/profile/             - token usage metrics (append-only)
 */

/**
 * Archive previous pipeline run before cleanup.
 * Moves key artifacts to .mpl/archive/{pipeline_id}/ for traceability.
 * @param {string} cwd
 */
function archivePreviousRun(cwd) {
  const prevState = readState(cwd);
  if (!prevState || !prevState.pipeline_id) return;

  const archiveDir = join(cwd, '.mpl', 'archive', prevState.pipeline_id);
  try {
    mkdirSync(archiveDir, { recursive: true });

    // Archive key files (best-effort, skip missing)
    const toArchive = [
      ['state.json', '.mpl/state.json'],
      ['PLAN.md', '.mpl/PLAN.md'],
    ];

    for (const [name, relPath] of toArchive) {
      const src = join(cwd, relPath);
      if (existsSync(src)) {
        writeFileSync(
          join(archiveDir, name),
          readFileSync(src, 'utf-8')
        );
      }
    }

    // Write archive metadata
    writeFileSync(
      join(archiveDir, 'meta.json'),
      JSON.stringify({
        pipeline_id: prevState.pipeline_id,
        archived_at: new Date().toISOString(),
        final_phase: prevState.current_phase,
        phases_completed: prevState.phases_completed || 0,
        gate_results: prevState.gate_results,
      }, null, 2) + '\n'
    );
  } catch {
    // Archive failure is non-fatal
  }
}

/**
 * Clean pipeline-scoped artifacts before starting a new pipeline.
 * Preserves all project-scoped data (config, memories, cache, profile).
 * @param {string} cwd - Working directory
 */
export function cleanPipelineScope(cwd) {
  // Archive previous run first
  archivePreviousRun(cwd);

  for (const relPath of PIPELINE_SCOPE_PATHS) {
    const fullPath = join(cwd, relPath);
    if (!existsSync(fullPath)) continue;

    try {
      rmSync(fullPath, { recursive: true, force: true });
    } catch {
      // Non-fatal: log but continue
      process.stderr.write(`[mpl-state] cleanup failed: ${relPath}\n`);
    }
  }
}

export function initState(cwd, featureName, runMode = 'full', ppHint = null) {
  // F-39: Clean pipeline-scoped artifacts before initializing new pipeline
  cleanPipelineScope(cwd);

  // H5: Load config overrides
  let config = {};
  try {
    config = loadConfig(cwd);
  } catch {
    // Config load failed, use defaults
  }

  const now = new Date().toISOString();
  const dateStr = now.slice(0, 10).replace(/-/g, '');
  // M1: Support Korean/CJK characters in slug
  const slug = featureName.toLowerCase()
    .replace(/[^a-z0-9가-힣ぁ-ゔァ-ヴ\u4e00-\u9fff]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40);

  const isNear = ppHint === 'near';
  const isMid = ppHint === 'mid';

  const maxFixLoops = config.max_fix_loops ?? (isNear ? 3 : isMid ? 5 : 10);
  const convergenceConfig = config.convergence ?? {};

  const ppPrefix = isNear ? 'near-' : isMid ? 'mid-' : '';
  return writeState(cwd, {
    ...DEFAULT_STATE,
    pipeline_id: `mpl-${ppPrefix}${dateStr}-${slug}`,
    run_mode: runMode === 'auto' ? 'auto' : runMode,
    pp_proximity: null,            // Set by Triage after Quick Scope Scan
    current_phase: isNear ? 'phase1a-research' : isMid ? 'small-plan' : 'phase1a-research',
    max_fix_loops: maxFixLoops,
    convergence: {
      ...DEFAULT_STATE.convergence,
      ...convergenceConfig
    },
    research: {
      ...DEFAULT_STATE.research,
      mode: isMid ? 'light' : 'full'
    },
    started_at: now
  });
}

/**
 * Check convergence of fix loop pass rates
 * Enhanced in v3: stagnation detection with variance, regression detection, strategy suggestions
 * @param {object} state - Current MPL state
 * @returns {{ status: string, delta?: number, suggestion?: string }}
 */
export function checkConvergence(state) {
  const conv = state?.convergence;
  if (!conv) return { status: 'insufficient_data' };

  const { pass_rate_history, stagnation_window = 3, min_improvement = 0.05, regression_threshold = -0.1 } = conv;
  if (!Array.isArray(pass_rate_history) || pass_rate_history.length < 2) return { status: 'insufficient_data' };

  const windowSize = Math.min(stagnation_window, pass_rate_history.length);
  const recent = pass_rate_history.slice(-windowSize);
  const latest = recent[recent.length - 1];
  const earliest = recent[0];
  const improvement = latest - earliest;

  // v3: Regression detection (delta < -10%)
  if (improvement < regression_threshold) {
    return {
      status: 'regressing',
      delta: improvement,
      suggestion: 'Pass rate is declining. Consider reverting to last known good state or reviewing Phase 0 artifacts.'
    };
  }

  // v3: Stagnation detection with variance check
  if (recent.length >= stagnation_window) {
    // Calculate variance of recent pass rates
    const mean = recent.reduce((a, b) => a + b, 0) / recent.length;
    const variance = recent.reduce((sum, val) => sum + Math.pow(val - mean, 2), 0) / recent.length;

    if (variance < 0.0025 && improvement < min_improvement) {
      // variance < 5% (0.05^2 = 0.0025) AND no meaningful improvement
      return {
        status: 'stagnating',
        delta: improvement,
        suggestion: 'Fix loop is not making progress. Try a different strategy: change implementation approach or consult Phase 0 artifacts.'
      };
    }

    if (improvement < min_improvement) {
      return { status: 'stagnating', delta: improvement, suggestion: 'Improvement is below threshold. Consider changing fix strategy.' };
    }
  }

  return { status: 'improving', delta: improvement };
}

/**
 * Deep merge two objects (shallow for arrays, with prototype pollution guard)
 */
export function deepMerge(target, source) {
  const result = { ...target };
  for (const key of Object.keys(source)) {
    // Prototype pollution guard
    if (DANGEROUS_KEYS.has(key)) continue;

    if (
      source[key] &&
      typeof source[key] === 'object' &&
      !Array.isArray(source[key]) &&
      target[key] &&
      typeof target[key] === 'object' &&
      !Array.isArray(target[key])
    ) {
      result[key] = deepMerge(target[key], source[key]);
    } else {
      result[key] = source[key];
    }
  }
  return result;
}
